---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-data
  namespace: test-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  #storageClassName: lvms-vg1