---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-mongodb
  namespace: test-mongodb
spec:
  serviceName: test-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: test-mongodb
  template:
    metadata:
      labels:
        app: test-mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: test-mongodb
          image: quay.io/mongodb/mongodb-community-server:7.0.6-ubi8
          command:
            - /bin/sh
            - -c
            - mongod --bind_ip 0.0.0.0 --port 27017
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
            limits:
              memory: 1Gi
          ports:
            - containerPort: 27017
              protocol: TCP
              name: db
          readinessProbe:
            exec:
              command:
                  - /bin/sh
                  - -c
                  - "mongosh --eval \"db.runCommand({hello: 1})\""
            initialDelaySeconds: 30
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 3
            failureThreshold: 10
          volumeMounts:
            - name: db-data
              mountPath: /data/db
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data